name: file_uploader_utils
description: common test/example utils for file uploader packages
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  en_file_uploader:
    path: ../../en_file_uploader
  path_provider: ^2.0.2
  http: ^1.3.0

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^5.1.0

dependency_overrides:
  en_file_uploader:
    git:
      url: https://github.com/pnm1133/file_uploader.git
      path: en_file_uploader
